# Site settings
title: Open Electioneering
email: openelectioneering@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    We're two researchers looking for patterns in election data!
    Currently in stealth mode.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: aaronsdevera
github_username:  openelectioneering

# Build settings
markdown: kramdown